### ISSUE TITLE
circle_points: TypeError: 'Actor' object is not subscriptable

### ISSUE THREAD

**Issue by stbaumg** [QuirkyCort/pgzhelper#11]
The edit below fixes the error:

  @staticmethod
  def circle_points(x, y, radius, points):
      rSquare = radius ** 2

      i = 0
      for point in points:
        try:
          px = point[0]
          py = point[1]
        except (KeyError, TypeError):
          px = point.x
          py = point.y
        dSquare = (px - x)**2 + (py - y)**2

        if dSquare < rSquare:
          return i
        i += 1

      return -1

**Comment by QuirkyCort** [comment]
Thanks. There are a few other places with the same issue. Should all be fixed now.
