### ISSUE TITLE
actor images doesnt register enough photos 

### ISSUE THREAD

**Issue by gggaming373** [QuirkyCort/pgzhelper#8]
i wanted to make a intro to my game and i need to animate it so i made a flip book kinda stuff like every frame is a photo and i tried to animate it there are 301 images but it only gets some of them other dont show when i do .animate

**Comment by QuirkyCort** [comment]
Are you able to share your code + images?

**Comment by gggaming373** [comment]
> Are you able to share your code + images?

well it has been a while bu here is the project file : https://github.com/gggaming373/BladeSU-
idk if it hahs that code which ran the intro and the images

**Comment by QuirkyCort** [comment]
Doesn't look like the right code. Can't replicate the problem.

**Comment by QuirkyCort** [comment]
Closed as the problem can't be replicated.
