### ISSUE TITLE
Idea: Can you add transparency/opacity to actors?

### ISSUE THREAD

**Issue by 4unduck** [QuirkyCort/pgzhelper#9]
Hello, i'm a new PGZero developer that hasn't even published one game yet. But it's not the deal.
Well, can you add an attribute "opacity (or transparency)" to actors? That would definitely help with the flash effect. Or does it already exist in PGZero?

**Comment by QuirkyCort** [comment]
I see that the opacity attribute has already been added to pygame zero on github, but it's not in the release yet.

Since the feature is in pygame zero, it's not something that I would add to pgzhelper.
